version: '3'

services:
  postgres:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: postgres
    container_name: ${DB_CONTAINER_NAME}
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - ${DB_PORT}

  flask-app:
    build:
      context: backend
      target: builder
    stop_signal: SIGINT
    ports:
      - '8000:8000'
    container_name: flask-app-container
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
    depends_on:
      - postgres
 
  chat-app:
    build:
      context: frontend
    ports:
      - '3000:3000'
    container_name: chat-app-container
    depends_on:
      - flask-app
