apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  DB_NAME: {{ .Values.configmap.DB_NAME }}
  DB_PORT: '{{ .Values.configmap.DB_PORT }}'
  DB_CONTAINER_NAME: {{ .Values.configmap.DB_CONTAINER_NAME }}
