apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresService.name }}
spec:
  selector:
    app: {{ .Values.postgresService.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.postgresService.port }}
      targetPort: {{ .Values.postgresService.targetPort }}
