apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flaskAppService.name }}
spec:
  selector:
    app: {{ .Values.flaskAppService.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.flaskAppService.port }}
      targetPort: {{ .Values.flaskAppService.targetPort }}
