apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.flaskAppDeployment.name }}
spec:
  replicas: {{ .Values.flaskAppDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.flaskAppDeployment.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.flaskAppDeployment.app }}
    spec:
      containers:
        - name: {{ .Values.flaskAppDeployment.containerName }}
          image: {{ .Values.flaskAppDeployment.image }}
          imagePullPolicy: {{ .Values.flaskAppDeployment.pullPolicy }}
          ports:
            - containerPort: {{ .Values.flaskAppDeployment.containerPort }}
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: password
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_PORT
            - name: DB_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_CONTAINER_NAME
