apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chatAppService.name }}
spec:
  selector:
    app: {{ .Values.chatAppService.app }}
  ports:
    - protocol: TCP
      port: {{ .Values.chatAppService.port }}
      targetPort: {{ .Values.chatAppService.targetPort }}
